#!/usr/local/bin/bash

dir=$1

for i in $dir/*
do
    while read -r line
    do
        v=$( grep ' total of ' )
        printf "$v\n";
        b=$( sed 's/.* total of //' $v )
        printf "$b\n";
    done < $i
done
